config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get '/dashboard', to: 'pages#dashboard'
  
  resources :movies, only: [:index, :show]
  resources :lists do
    resources :bookmarks, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
  resources :reviews, only: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movie_genres
  has_many :movies, through: :movie_genres
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
  belongs_to :user, optional: true
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movie_genres
  has_many :lists, through: :bookmarks 
  has_many :genres, through: :movie_genres
  validates :overview, uniqueness: true, presence: true
  # searchkick
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :lists, dependent: :destroy
  has_many :movies, through: :bookmarks  
  
  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

 # Pundit: white-list approach.
 after_action :verify_authorized, except: :index, unless: :skip_pundit?
 after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

 # Uncomment when you *really understand* Pundit!
 # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
 # def user_not_authorized
 #   flash[:alert] = "You are not authorized to perform this action."
 #   redirect_to(root_path)
 # end

 private

 def skip_pundit?
  devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
end

def configure_permitted_parameters
  # For additional fields in app/views/devise/registrations/new.html.erb
  devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

  # For additional in app/views/devise/registrations/edit.html.erb
  devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :find_list, only: [ :new, :create ]
 

  def new
    @bookmark = Bookmark.new
    authorize @bookmark
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    authorize @bookmark
    if @bookmark.save!
      redirect_to @list
    else 
      render "new"
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.delete
    redirect_to @bookmark.list
    authorize @bookmark
  end

  private
  
  def find_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  skip_after_action :verify_authorized, only: %i[show]
  skip_before_action :authenticate_user!, only: %i[show]


  def index 
    @lists = policy_scope(List).where(user: current_user)
  end

  def show
    @list = List.find(params[:id])
    @movies = Movie.all
    @bookmark = Bookmark.new
    @review = Review.new
    @reviews = @list.reviews
    authorize @list
  end

  def new
    @list = List.new
    @list.user = current_user
    authorize @list
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    authorize @list
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)
    redirect_to list_path
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path(@lists)
  end



  private

  # def find_restaurants
  #   @restaurant = Restaurant.find(params[:id])
  # end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    if params[:query].present?
      @movies = Movie.where("title ILIKE ?", "%#{params[:query]}%")
    else
      @movies = policy_scope(Movie).order(rating: :desc).limit(3)
    end
    @allmovies = policy_scope(Movie).all.paginate(page: params[:page], per_page: 8)
  end

  def show
    @movie = Movie.find(params[:id])
    authorize @movie
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    
  end

  def dashboard
    @lists = List.where(user: current_user)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_list, except: [:destroy]
  def new
    @review = Review.new
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @list = List.find(params[:list_id])
    @review.list = @list
    authorize @review

    if @review.save
       redirect_to list_path(@list)
    else 
      render "list/show"
    end
  end
    

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to list_path(@review.list)
    authorize @review
  end

  private

  def find_list
  @list = List.find(params[:list_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/new.html.erb
<div class="form-banner">
</div>
<div class="bg">
  <div class="glass">
    <div class="form-container">
     <div class="bookmark-container">
      <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
        <div class="form-inputs">
          <%= f.input :comment %>
          <%= f.association :movie, label_method: :title, value_method: :id, include_blank: false %>
        </div>
        <div class="form-actions">
          <%= f.button :submit, class: "btn btn-outline-dark" %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class ="form-container">
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
     <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-outline-dark" %>
  </div>
<% end %>
</div>

app/views/lists/edit.html.erb
<%= render 'form', list: @list %>

app/views/lists/index.html.erb
<div class = "home-banner">
<div class = "hb-container">
 <% if user_signed_in? %>
<h1><%= current_user.first_name %>'s Movie list</h1>
</div>
<% end %>
</div>


<div class = "d-flex justify-content-around my-box-light flex-wrap mb-2">
<% @lists.each do |list| %>
<div class="card bg-dark text-white">
   <%= image_tag list.photo, class: "card-img" %>
  <div class="card-img-overlay">
    <h4 class="card-title"> <%= link_to list.name, list_path(list), class: "white-text" %></h4>
       <p class="item">
    <%= link_to edit_list_path(list) do%>
      <i class="far fa-edit"></i>
      <% end %>
    <%= link_to list_path(list), method: :delete do%>
    <i class="fas fa-trash-alt"></i>
    <% end %>
     </p>
  </div>
</div>
 <% end %>
</div>

app/views/lists/new.html.erb
<div class="form-banner">
</div>
<div class="bg">
  <div class="glass">
   <div class="list-new-container">
    <div class ="form-container">
      <%= simple_form_for(@list) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
        <div class="form-inputs">
          <%= f.input :name %>
          <%= f.input :photo, as: :file %>
        </div>
        <div class="form-actions">
          <%= f.button :submit, class: "btn btn-outline-dark" %>
        </div>
      <% end %>
    </div>
   </div> 
  </div>
</div>

app/views/lists/show.html.erb
<div class="card-category">
  <div class="glide">
    <div class="glide__track" data-glide-el="track">
      <ul class="glide__slides">
       <% @list.bookmarks.each do |bookmark| %>
    <div class="movie_card" id="bright">
      <div class="info_section">
        <%# <%= link_to "x", bookmark_path(bookmark), method: :delete, class: "delete-move" %> 
        <div class="movie_header">
          <%= image_tag bookmark.movie.poster_url, alt: "movie poster", class: "locandina"%>
          <h1><%= bookmark.movie.title %></h1>
          <h4><%= bookmark.movie.date[0..3]%></h4>
          <h4><%= "⭐️" * bookmark.movie.rating %></h4>
          <p class="type"><i class="fas fa-quote-left"></i><%= bookmark.comment %></p>
        </div>
        <div class="movie-description">
          <div class="overview-text"><%= bookmark.movie.overview %></div>
        </div>
        <div class="movie_social">
        </div>
      </div>
      <div class="blur_back bright_back" style="background-image: url('<%= bookmark.movie.poster_url %>')"></div>
    </div>
  <% end %>

     </ul>
    </div>
  </div>
</div>

<div class ="sliders-container d-flex">
<div class="select-movie">
<div class="add-btn-container">
<% if policy(@bookmark).new? %>
<div class="add-btn"><h1><%= link_to "+", new_list_bookmark_path(@list)%></h1></div>
<% end %>
</div>
</div>
  <div class="selected-movies">
  <div class="glide2">
    <div class="glide__track" data-glide-el="track">
      <ul class="glide__slides">
        <% @list.bookmarks.each do | bookmark | %>
          <li class="glide__slide"><%= image_tag bookmark.movie.poster_url, alt: "movie poster", class: "movie-slide"%></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>  
</div>



<div class="container">
  <div class="card-show-title">
    <h1>Movies 🎬</h1>
    <p></p>
  </div>


  <div class="row">
    <div class="col-6 part-a">
      <% @reviews.each do |review|%>
      <div class="reviews-stars">
      <div class="mt-3">
         <div class="stars-container">
        <% 5.times do |i| %>
          <% if review.rating > i %>
             <i class="fas fa-star"  style="color:yellow"></i>
          <% else %>
            <i class="fas fa-star"></i>
          <% end %>
        <% end %>
          </div>  
         <div class="review-content"> 
         <%= review.content%>
           <div class="review-options"> 
           <%= review.created_at.strftime("%d#{"th"} %b %Y %H:%M") %>
            <%= link_to "delete", review_path(review), method: :delete %>
            </div>
         </div>
       </div>
      </div>    
            <hr>
          <% end %>
        </div>
        <div class="col-6 part-b">
          <div class="movie-form">
            <h3>Review for list</h3>
            <%= simple_form_for [@list, @review] do |f| %>
              <%= f.input :content, placeholder: 'Add your comment' %>
              <div class="form-group row" id="star">
                <label for="review_content">Rating</label>
                  <div class="star-song-rating">
                    <% 5.times do |i| %>
                      <input type="radio" name="review[rating]"  value="<%= i + 1 %>" <%= "checked" if i == 2 %> />
                    <% end %>
                  </div>
                </div>
              <%= f.submit "Add review", class: "btn btn-outline-dark" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/movies/index.html.erb
 <div class="movie-banner">
 <div class="movie-wrapper d-flex justify-content-around my-box-light flex-wrap mb-2">
    <% @movies.each do |movie| %>
      <div class="search-container-glass">
        <%= image_tag movie.poster_url, :width => '300px', :height => '200px', alt: "movie poster", class: "img" %>
        <p class="movie-card-text">
          <div class="d-flex">
            <h4><i class="fas fa-star"></i></h4>
            <h4><%= movie.rating %></h4>
            <h5>/10</h5>
          </div>
          <h6><%= movie.title %></h6>
          <button class="btn"><%= link_to "Discover", movie_path(movie), class: "white-text" %></button>
        </p>
      </div>
   
    <% end %>
  </div>
 </div>

<div class="movie-search-container">
<div class="d-flex">
  <%= form_tag movies_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a movie"
    %>
    <%= submit_tag "Search", class: "btn btn-primary"%>
   <% end %>  
  </div>
</div>

  <div class="list-container">
    <h1>Movies 🎬</h1>
  </div>
  <div class="movie-wrapper d-flex justify-content-around my-box-light flex-wrap mb-2">
    <% @allmovies.each do |allmovie| %>
      <div class="container-glass">
        <%= image_tag allmovie.poster_url, :width => '300px', :height => '200px', alt: "movie poster", class: "img" %>
        <p class="movie-card-text">
          <div class="d-flex">
            <h4><i class="fas fa-star"></i></h4>
            <h4><%= allmovie.rating %></h4>
            <h5>/10</h5>
          </div>
          <h6><%= allmovie.title %></h6>
          <button class="btn"><%= link_to "Discover", movie_path(allmovie), class: "white-text" %></button>
        </p>
      </div>
   
    <% end %>
  </div>
<div class="page-navigation">
<%= will_paginate @allmovies, :previous_label => '&lt', :next_label => '&gt', renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

app/views/movies/show.html.erb
<div class="card-category">
    <div class="movie_card" id="bright">
      <div class="info_section">
        <%# <%= link_to "x", bookmark_path(bookmark), method: :delete, class: "delete-move" %> 
        <div class="movie_header">
          <%= image_tag @movie.poster_url, alt: "movie poster", class: "locandina"%>
          <h1><%= @movie.title %></h1>
          <h4><%=@movie.date[0..3]%></h4>
          <h4><%= "⭐️" * @movie.rating %></h4>
        </div>
        <div class="movie-description">
          <div class="overview-text"><%= @movie.overview %></div>
        </div>
        <div class="movie_social">
        </div>
      </div>
      <div class="blur_back bright_back" style="background-image: url('<%= @movie.poster_url %>')"></div>
    </div>
</div>
<div class="content">
</div>

app/views/pages/dashboard.html.erb
 <% if user_signed_in? %>
<div class="welcome-user"><h5>Welcome, <%= current_user.first_name %></h5></div>
<% end %>

<div class="action-container d-flex">
<div class="part-1">
<div class="icon"> 
<i class="fas fa-search"></i>
</div>
<h5><%= link_to "Search Movies",  movies_path %></h5>
</div>
<div class="part-2">
<div class="icon"> 
<i class="fas fa-film"></i>
</div>
<h5><%= link_to "All Movie Lists", lists_path %></h5>
</div>
<div class="part-3">
<div class="icon"> 
<i class="fas fa-file-video"></i>
</div>
<h5><%= link_to "New List", new_list_path %></h5>
</div>
</div>

app/views/pages/home.html.erb
<div class ="background-home">
</div>
<div class="message">
  <section class='section'>
    <div class='masthead-image' id='master-container'>
      <div class='content center'>
        <h1 id='master'>
          <div>Your</div>
          <div id='master-container-scroller'>
            <div class='master-container-scroller_item'>
              <a class='cta-link' href='#'>Favorite</a>.
            </div>
            <div class='master-container-scroller_item'>
              <a class='cta-link' href='/dashboard'>Classical</a>.
            </div>
            <div class='master-container-scroller_item'>
              <a class='cta-link' href='#'>Sunday</a>.
            </div>
            <div class='master-container-scroller_item'>
              <a class='cta-link' href='#'>Anime</a>.
            </div>
            <div class='master-container-scroller_item'>
              <a class='cta-link' href='#'>Happy</a>.
            </div>
            <div class='master-container-scroller_item'>
              <a class='cta-link' href='#'>Memoriable</a>.
            </div>
            <div class='master-container-scroller_item'>
              <a class='cta-link' href='#'>Japanese</a>.
            </div>
            <div class='master-container-scroller_item'>
              <a class='cta-link' href='#'>Best</a>.
            </div>
            <div class='master-container-scroller_item'>
              <a class='cta-link' href='/dashboard'>unforgettable</a>.
            </div>
            <div class='master-container-scroller_item'>Friend's</div>
          </div>
          <div>Movie List</div>
        </h1>
      </div>
    </div>
  </section>
  <div class="watch-button">
    <button><%= link_to "Watch", dashboard_path %></button>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [list, @review] do |f| %>
<%= f.association :list %>
<%= f.input :content, placeholder: 'Add your comment' %>
<%= f.input :rating, placeholder: 'Add your rating', collection: 1..5, id: "example"   %>
<%= f.submit "Add review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/new.html.erb
<div class="review-container">
<%= simple_form_for [ @list, @review ] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    2022 Allllsha
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to dashboard_path, class: "navbar-brand" do %>
    <%= image_tag asset_url('logon.png') %> Movie List
  <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "New List", new_list_path(@lists), class: "newlist"%>
          </li>
          
          <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "logout"%>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
             <%= link_to "Home", lists_path(@lists), class: "dropdown-item" %>
          <%= link_to "New List", new_list_path(@lists), class: "dropdown-item" %>
          <%= link_to "All lists", lists_path(@lists), class: "dropdown-item" %>
          <%= link_to "Search Movie", movies_path(@movies), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>